# Generated by Django 3.2.4 on 2021-06-13 03:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('happyd1g1t', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Happiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happiness_level', models.IntegerField(choices=[(1, 'Pleasure'), (2, 'Passion'), (3, 'Purpose'), (4, 'Ultimate Good')], default=0)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happyd1g1t.user')),
            ],
            options={
                'ordering': ['happiness_level'],
            },
        ),
    ]
