# Generated by Django 3.2.4 on 2021-06-14 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('happyd1g1t', '0003_alter_happiness_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='happiness',
            name='happiness_level',
            field=models.IntegerField(choices=[(1, 'Highly Unsatisfactory'), (2, 'Mostly Unsatisfactory'), (3, 'Somewhat Unsatisfactory'), (4, 'Unsatisfactory'), (5, 'Neutral'), (6, 'Satisfactory'), (7, 'Somewhat Satisfactory'), (8, 'Moderately Satisfactory'), (9, 'Mostly Satisfactory'), (10, 'Highly Satisfactory')], default=5),
        ),
        migrations.AlterField(
            model_name='happiness',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
