# Generated by Django 3.2.4 on 2021-06-14 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('happyd1g1t', '0005_auto_20210614_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='happiness',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='happyd1g1t.team'),
        ),
    ]
