# Generated by Django 3.2.4 on 2021-06-14 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('happyd1g1t', '0006_happiness_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='happiness',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happyd1g1t.team'),
        ),
    ]
