# Generated by Django 3.2.4 on 2021-06-15 03:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyd1g1t', '0008_alter_happiness_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='happiness',
            options={'ordering': ['date']},
        ),
        migrations.RenameField(
            model_name='happiness',
            old_name='user',
            new_name='employee',
        ),
        migrations.AlterField(
            model_name='happiness',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date'),
        ),
        migrations.AlterUniqueTogether(
            name='happiness',
            unique_together={('employee', 'date')},
        ),
        migrations.RemoveField(
            model_name='happiness',
            name='happiness_level',
        ),
        migrations.RemoveField(
            model_name='happiness',
            name='team',
        ),
    ]
