# Generated by Django 3.2.4 on 2021-06-15 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyd1g1t', '0009_auto_20210615_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='happiness',
            name='happiness_level',
            field=models.IntegerField(choices=[(1, 'Highly Unsatisfactory'), (2, 'Mostly Unsatisfactory'), (3, 'Somewhat Unsatisfactory'), (4, 'Unsatisfactory'), (5, 'Neutral'), (6, 'Satisfactory'), (7, 'Somewhat Satisfactory'), (8, 'Moderately Satisfactory'), (9, 'Mostly Satisfactory'), (10, 'Highly Satisfactory')], default=5),
        ),
    ]
